services:
  jupyter:
    image: stock-market-image
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
          - JUPYTER_SERVER_PWD=${JUPYTER_SERVER_PWD}

    # mem_limit: 1.5g
    # memswap_limit: 2g
    # cpus: "0.5"
    
    command: |
      conda run --name time-series-env start-notebook.py
      --ServerApp.ip=0.0.0.0
      --ServerApp.token=${JUPYTER_SERVER_PWD}
      --ServerApp.notebook_dir=/home/jovyan/work/notebooks

    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/jovyan/work/data
      - ./models:/home/jovyan/work/models

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.19.0
    command: mlflow server --host 0.0.0.0
    
    restart: always
    ports:
      - 5000:5000
    volumes:
      - mlflow-data:/mlflow

volumes:
  mlflow-data: