services:
  jupyter:
    image: stock-market-image
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
          - JUPYTER_SERVER_PWD=${JUPYTER_SERVER_PWD:-}

    # Minimum System Requirements:         
    # mem_limit: 1.5g
    # memswap_limit: 2g
    # cpus: "0.5"
    
    # Comment this part out if you have problems with GPU support
    # For Nvidia hardware you can enable GPU-acceleration by following the instructions on
    # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]    
                  
    environment:
      - MLFLOW_TRACKING_URI=http://stock-market-mlflow-1:5000
      - GIT_PYTHON_REFRESH=quiet

    command: |
      conda run --name time-series-env start-notebook.py
      --ServerApp.ip=0.0.0.0
      --ServerApp.root_dir=/home/jovyan/work/notebooks
      --IdentityProvider.token=${JUPYTER_SERVER_PWD:-}

    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/jovyan/work/data
      - ./models:/home/jovyan/work/models
      - ./notebooks:/home/jovyan/work/notebooks

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.19.0

    environment:
      - MLFLOW_BACKEND_STORE_URI=file:///mlflow/mlruns
      - MLFLOW_ARTIFACTS_DESTINATION=/mlflow/mlartifacts
      - MLFLOW_HOST=0.0.0.0

    command: mlflow server
    
    restart: always
    ports:
      - 5000:5000
    volumes:
      - mlflow-data:/mlflow

volumes:
  mlflow-data: