name: time-series-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - alembic=1.13.3
  - aniso8601=9.0.1
  - archspec=0.2.3
  - arrow-cpp=17.0.0
  - asttokens=2.0.5
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - bcrypt=3.2.0
  - blas=1.0
  - blinker=1.9.0
  - boltons=24.1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - cachetools=5.3.3
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - comm=0.2.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - contourpy=1.3.1
  - cpp-expected=1.1.0
  - cryptography=43.0.3
  - cycler=0.11.0
  - databricks-sdk=0.33.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - deprecated=1.2.13
  - distro=1.9.0
  - docker-py=7.1.0
  - executing=0.8.3
  - expat=2.6.4
  - flask=3.1.0
  - fmt=9.1.0
  - fonttools=4.55.3
  - freetype=2.12.1
  - frozendict=2.4.2
  - frozenlist=1.5.0
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glog=0.5.0
  - google-auth=2.29.0
  - graphene=3.3
  - graphql-core=3.2.3
  - graphql-relay=3.2.0
  - greenlet=3.1.1
  - gunicorn=22.0.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.11.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - mako=1.2.3
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - menuinst=2.2.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mlflow=2.18.0
  - multidict=6.1.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.2
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - opentelemetry-api=1.26.0
  - opentelemetry-sdk=1.26.0
  - opentelemetry-semantic-conventions=0.47b0
  - orc=2.0.1
  - packaging=24.2
  - pandas=2.2.3
  - paramiko=3.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.2.0
  - protobuf=4.25.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=17.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.15.1
  - pynacl=1.5.0
  - pyopenssl=24.2.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.8
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2022.04.01
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - rsa=4.7.2
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s2n=1.3.27
  - scikit-learn=1.5.2
  - scipy=1.15.1
  - seaborn=0.13.2
  - setuptools=75.1.0
  - simdjson=3.10.1
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - spdlog=1.11.0
  - sqlalchemy=2.0.37
  - sqlite=3.45.3
  - sqlparse=0.5.2
  - stack_data=0.2.0
  - statsmodels=0.14.4
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - truststore=0.10.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.44.0
  - wrapt=1.17.0
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - altair==5.5.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - baostock==0.8.9
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - colorama==0.4.6
      - defusedxml==0.7.1
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - fqdn==1.5.1
      - fsspec==2025.2.0
      - html5lib==1.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-events==0.12.0
      - jupyter-server==2.15.0
      - jupyter-server-mathjax==0.2.6
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.13
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mistune==3.1.1
      - mpmath==1.3.0
      - multitasking==0.0.11
      - narwhals==1.27.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbdime==4.0.2
      - nbformat==5.10.4
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - peewee==3.17.9
      - prometheus-client==0.21.1
      - pydeck==0.9.1
      - python-json-logger==3.2.1
      - referencing==0.36.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - streamlit==1.42.0
      - sympy==1.13.1
      - tenacity==9.0.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - toml==0.10.2
      - torch==2.6.0
      - triton==3.2.0
      - types-python-dateutil==2.9.0.20241206
      - uri-template==1.3.0
      - watchdog==6.0.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - widgetsnbextension==4.0.13
      - yfinance==0.2.52